# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `job-iteration` gem.
# Please instead update this file by running `bin/tapioca gem job-iteration`.


# source://job-iteration//lib/job-iteration/version.rb#3
module JobIteration
  extend ::JobIteration

  # Configures a delay duration to wait before resuming an interrupted job.
  # Defaults to nil which means interrupted jobs will be retried immediately.
  # This value will be ignored when an interruption is raised by a throttle enumerator,
  # where the throttle backoff value will take precedence over this setting.
  #
  # @example
  #
  #   JobIteration.default_retry_backoff = 10.seconds
  #
  # source://job-iteration//lib/job-iteration.rb#58
  def default_retry_backoff; end

  # Configures a delay duration to wait before resuming an interrupted job.
  # Defaults to nil which means interrupted jobs will be retried immediately.
  # This value will be ignored when an interruption is raised by a throttle enumerator,
  # where the throttle backoff value will take precedence over this setting.
  #
  # @example
  #
  #   JobIteration.default_retry_backoff = 10.seconds
  #
  # source://job-iteration//lib/job-iteration.rb#58
  def default_retry_backoff=(_arg0); end

  # Set if you want to use your own enumerator builder instead of default EnumeratorBuilder.
  #
  # @example
  #
  #   class MyOwnBuilder < JobIteration::EnumeratorBuilder
  #   # ...
  #   end
  #
  #   JobIteration.enumerator_builder = MyOwnBuilder
  #
  # source://job-iteration//lib/job-iteration.rb#84
  def enumerator_builder; end

  # Set if you want to use your own enumerator builder instead of default EnumeratorBuilder.
  #
  # @example
  #
  #   class MyOwnBuilder < JobIteration::EnumeratorBuilder
  #   # ...
  #   end
  #
  #   JobIteration.enumerator_builder = MyOwnBuilder
  #
  # source://job-iteration//lib/job-iteration.rb#84
  def enumerator_builder=(_arg0); end

  # Returns the value of attribute interruption_adapter.
  #
  # source://job-iteration//lib/job-iteration.rb#60
  def interruption_adapter; end

  # Overrides interruption checks based on queue adapter.
  #
  # @deprecated - Use JobIteration::InterruptionAdapters.register(:foo, callable) instead.
  #
  # source://job-iteration//lib/job-iteration.rb#64
  def interruption_adapter=(adapter); end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://job-iteration//lib/job-iteration.rb#16
  def logger=(_arg0); end

  # Use this to _always_ interrupt the job after it's been running for more than N seconds.
  # This setting will make it to always interrupt a job after it's been iterating for 5 minutes.
  # Defaults to nil which means that jobs will not be interrupted except on termination signal.
  #
  # This setting can be overriden by using the inheritable per-class job_iteration_max_job_runtime setting. At runtime,
  # the lower of the two will be used.
  # Note that if a sub-class overrides its parent's setting, only the global and sub-class setting will be considered,
  # not the parent's.
  #
  # @example
  #
  #   JobIteration.max_job_runtime = 5.minutes
  # @example
  #
  #   class MyJob < ActiveJob::Base
  #   include JobIteration::Iteration
  #   self.job_iteration_max_job_runtime = 1.minute
  #   # ...
  # @example
  #
  #   class ChildJob < MyJob
  #   self.job_iteration_max_job_runtime = 3.minutes # MyJob's 1.minute will be discarded.
  #   # ...
  #
  # source://job-iteration//lib/job-iteration.rb#48
  def max_job_runtime; end

  # Use this to _always_ interrupt the job after it's been running for more than N seconds.
  # This setting will make it to always interrupt a job after it's been iterating for 5 minutes.
  # Defaults to nil which means that jobs will not be interrupted except on termination signal.
  #
  # This setting can be overriden by using the inheritable per-class job_iteration_max_job_runtime setting. At runtime,
  # the lower of the two will be used.
  # Note that if a sub-class overrides its parent's setting, only the global and sub-class setting will be considered,
  # not the parent's.
  #
  # @example
  #
  #   JobIteration.max_job_runtime = 5.minutes
  # @example
  #
  #   class MyJob < ActiveJob::Base
  #   include JobIteration::Iteration
  #   self.job_iteration_max_job_runtime = 1.minute
  #   # ...
  # @example
  #
  #   class ChildJob < MyJob
  #   self.job_iteration_max_job_runtime = 3.minutes # MyJob's 1.minute will be discarded.
  #   # ...
  #
  # source://job-iteration//lib/job-iteration.rb#48
  def max_job_runtime=(_arg0); end

  # source://job-iteration//lib/job-iteration.rb#72
  def register_interruption_adapter(adapter_name, adapter); end

  class << self
    # source://job-iteration//lib/job-iteration.rb#19
    def logger; end
  end
end

# Builds Batch Enumerator based on ActiveRecord Relation.
#
# @see EnumeratorBuilder
#
# source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#4
class JobIteration::ActiveRecordBatchEnumerator
  include ::Enumerable

  # @return [ActiveRecordBatchEnumerator] a new instance of ActiveRecordBatchEnumerator
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#13
  def initialize(relation, columns: T.unsafe(nil), batch_size: T.unsafe(nil), timezone: T.unsafe(nil), cursor: T.unsafe(nil)); end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#27
  def each; end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#35
  def size; end

  private

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#122
  def column_value(value); end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#100
  def conditions; end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#94
  def cursor_value; end

  # Yields relations by selecting the primary keys of records in the batch.
  # Post.where(published: nil) results in an enumerator of relations like:
  # Post.where(published: nil, ids: batch_of_ids)
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#65
  def filter_relation_with_primary_key(primary_key_values); end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#41
  def next_batch; end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#81
  def pluck_columns(relation); end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#118
  def serialize_column_values!(column_values); end
end

# Utility class for the batch enumerator that manages the columns that need
# to be plucked. It ensures primary key columns are plucked so that records
# in the batch can be queried for efficiently.
#
# @see ActiveRecordBatchEnumerator
#
# source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#10
class JobIteration::ActiveRecordBatchEnumerator::ColumnManager
  # @param columns [Array<String,Symbol>, nil] - set of columns to select
  # @param relation [ActiveRecord::Relation] - relation to manage columns for
  # @return [ColumnManager] a new instance of ColumnManager
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#13
  def initialize(relation:, columns:); end

  # @return [Array<String>] The list of columns to be plucked. If no columns were specified, this
  #   list contains the fully qualified primary key column(s).
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#26
  def columns; end

  # @param column_values [Array<Array>] List of rows where each row contains values as determined by
  #   `pluck_columns`.
  # @return [Array<Array>] List where each item contains the primary key column values for the
  #   corresponding row. Values are guaranteed to be in the same order as
  #   the columns are listed in `primary_key`.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#47
  def pkey_values(column_values); end

  # @return [Array<String>] The full set of columns to be plucked from the relation. This is a
  #   superset of `columns` and is guaranteed to contain all of the primary
  #   key columns on the relation.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#37
  def pluck_columns; end

  # @return [Array<String>] The list of primary key columns for the relation. These columns are
  #   not qualified with the table name.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#31
  def primary_key; end

  # @param cursor [Array] A list of values for a single row, as determined by `pluck_columns`.
  # @return [Array] The same values that were passed in, minus any primary key column
  #   values that do not appear in `columns`.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#62
  def remove_missing_pkey_values(cursor); end

  private

  # Takes a set of primary key columns and adds them to `columns`.
  #
  # @note - mutates `columns`
  # @param columns [Array<String>] - set of columns to pluck
  # @param missing_columns [Array<String>] - set of missing pkey columns
  # @return [Hash<String:Integer>] A hash containing all of the values from `missing_columns` as its
  #   keys. Values are the position of those columns in `columns`.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#130
  def add_missing_pkey_columns!(missing_columns, columns); end

  # Figure out which primary key columns are already included in `columns`
  # and track their position in the array.
  #
  # @param columns [Array<String>] - list of columns
  # @return [Hash<String:Integer,nil>] A hash containing all of the fully qualified primary key columns as
  #   its keys. Values are the position of each column in the `columns`
  #   array. A `nil` value indicates the column is not present in `columns`.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#111
  def find_initial_primary_key_indices(columns); end

  # This method is responsible for initializing several instance variables:
  #
  # * `@pluck_columns` [Array<String>] -
  #       The set of columns to pluck.
  # * `@missing_pkey_count` [Integer] -
  #       The number of primary keys that were missing from `@columns`.
  # * `@primary_key_index_map` [Hash<String:Integer>] -
  #       Hash mapping all primary key columns to their position in
  #       `@pluck_columns`.
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#90
  def initialize_pluck_columns_and_pkey_positions; end

  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#69
  def qualify_column(column); end

  # @raise [ArgumentError]
  #
  # source://job-iteration//lib/job-iteration/active_record_batch_enumerator/column_manager.rb#73
  def validate_columns!(relation); end
end

# source://job-iteration//lib/job-iteration/active_record_batch_enumerator.rb#11
JobIteration::ActiveRecordBatchEnumerator::SQL_DATETIME_WITH_NSEC = T.let(T.unsafe(nil), String)

# Curious about how this works from the SQL perspective?
# Check "Pagination Done the Right way": https://bit.ly/2Rq7iPF
#
# source://job-iteration//lib/job-iteration/active_record_cursor.rb#6
class JobIteration::ActiveRecordCursor
  include ::Comparable

  # @raise [ArgumentError]
  # @return [ActiveRecordCursor] a new instance of ActiveRecordCursor
  #
  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#21
  def initialize(relation, columns = T.unsafe(nil), position = T.unsafe(nil)); end

  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#41
  def <=>(other); end

  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#67
  def next_batch(batch_size); end

  # Returns the value of attribute position.
  #
  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#9
  def position; end

  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#49
  def position=(position); end

  # Returns the value of attribute reached_end.
  #
  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#10
  def reached_end; end

  # Sets the attribute reached_end
  #
  # @param value the value to set the attribute reached_end to.
  #
  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#10
  def reached_end=(_arg0); end

  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#55
  def update_from_record(record); end

  protected

  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#88
  def conditions; end
end

# source://job-iteration//lib/job-iteration/active_record_cursor.rb#12
class JobIteration::ActiveRecordCursor::ConditionNotSupportedError < ::ArgumentError
  # @return [ConditionNotSupportedError] a new instance of ConditionNotSupportedError
  #
  # source://job-iteration//lib/job-iteration/active_record_cursor.rb#13
  def initialize; end
end

# Builds Enumerator based on ActiveRecord Relation. Supports enumerating on rows and batches.
#
# @see EnumeratorBuilder
#
# source://job-iteration//lib/job-iteration/active_record_enumerator.rb#7
class JobIteration::ActiveRecordEnumerator
  # @return [ActiveRecordEnumerator] a new instance of ActiveRecordEnumerator
  #
  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#10
  def initialize(relation, columns: T.unsafe(nil), batch_size: T.unsafe(nil), timezone: T.unsafe(nil), cursor: T.unsafe(nil)); end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#32
  def batches; end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#22
  def records; end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#41
  def size; end

  private

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#67
  def column_value(record, attribute); end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#53
  def cursor_value(record); end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#63
  def finder_cursor; end

  # source://job-iteration//lib/job-iteration/active_record_enumerator.rb#47
  def instrument_next_batch(cursor); end
end

# source://job-iteration//lib/job-iteration/active_record_enumerator.rb#8
JobIteration::ActiveRecordEnumerator::SQL_DATETIME_WITH_NSEC = T.let(T.unsafe(nil), String)

# CsvEnumerator makes it possible to write an Iteration job
# that uses CSV file as a collection to Iterate.
#
# @example
#   def build_enumerator(cursor:)
#   csv = CSV.open('tmp/files', { converters: :integer, headers: true })
#   JobIteration::CsvEnumerator.new(csv).rows(cursor: cursor)
#   end
#
#   def each_iteration(row)
#   ...
#   end
#
# source://job-iteration//lib/job-iteration/csv_enumerator.rb#15
class JobIteration::CsvEnumerator
  # Constructs CsvEnumerator instance based on a CSV file.
  #
  # @example
  #   csv = CSV.open('tmp/files', { converters: :integer, headers: true })
  #   JobIteration::CsvEnumerator.new(csv).rows(cursor: cursor)
  # @param csv [CSV] An instance of CSV object
  # @return [JobIteration::CsvEnumerator]
  #
  # source://job-iteration//lib/job-iteration/csv_enumerator.rb#22
  def initialize(csv); end

  # Constructs a enumerator on batches of CSV rows
  #
  # @return [Enumerator] Enumerator instance
  #
  # source://job-iteration//lib/job-iteration/csv_enumerator.rb#41
  def batches(batch_size:, cursor:); end

  # Constructs a enumerator on CSV rows
  #
  # @return [Enumerator] Enumerator instance
  #
  # source://job-iteration//lib/job-iteration/csv_enumerator.rb#32
  def rows(cursor:); end

  private

  # source://job-iteration//lib/job-iteration/csv_enumerator.rb#63
  def count_of_processed_rows(cursor); end

  # source://job-iteration//lib/job-iteration/csv_enumerator.rb#54
  def count_of_rows_in_file; end
end

# source://job-iteration//lib/job-iteration.rb#12
JobIteration::Deprecation = T.let(T.unsafe(nil), ActiveSupport::Deprecation)

# source://job-iteration//lib/job-iteration/enumerator_builder.rb#11
class JobIteration::EnumeratorBuilder
  extend ::Forwardable

  # @return [EnumeratorBuilder] a new instance of EnumeratorBuilder
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#33
  def initialize(job, wrapper: T.unsafe(nil)); end

  # Builds Enumerator from Active Record Relation and enumerates on batches, yielding Active Record Relations.
  # See documentation for #build_active_record_enumerator_on_batches.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#193
  def active_record_on_batch_relations(scope, cursor:, wrap: T.unsafe(nil), **args); end

  # Builds Enumerator from Active Record Relation and enumerates on batches of records.
  # Each Enumerator tick moves the cursor +batch_size+ rows forward.
  #
  # +batch_size:+ sets how many records will be fetched in one batch. Defaults to 100.
  #
  # For the rest of arguments, see documentation for #build_active_record_enumerator_on_records
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#192
  def active_record_on_batches(scope, cursor:, **args); end

  # Builds Enumerator from Active Record Relation. Each Enumerator tick moves the cursor one row forward.
  #
  # +columns:+ argument is used to build the actual query for iteration. +columns+: defaults to primary key:
  #
  #   1) SELECT * FROM users ORDER BY id LIMIT 100
  #
  # When iteration is resumed, +cursor:+ and +columns:+ values will be used to continue from the point
  # where iteration stopped:
  #
  #   2) SELECT * FROM users WHERE id > $CURSOR ORDER BY id LIMIT 100
  #
  # +columns:+ can also take more than one column. In that case, +cursor+ will contain serialized values
  # of all columns at the point where iteration stopped.
  #
  # Consider this example with +columns: [:created_at, :id]+. Here's the query will use on the first iteration:
  #
  #   1) SELECT * FROM `products` ORDER BY created_at, id LIMIT 100
  #
  # And the query on the next iteration:
  #
  #   2) SELECT * FROM `products`
  #        WHERE (created_at > '$LAST_CREATED_AT_CURSOR'
  #          OR (created_at = '$LAST_CREATED_AT_CURSOR' AND (id > '$LAST_ID_CURSOR')))
  #        ORDER BY created_at, id LIMIT 100
  #
  # As a result of this query pattern, if the values in these columns change for the records in scope during
  # iteration, they may be skipped or yielded multiple times depending on the nature of the update and the
  # cursor's value. If the value gets updated to a greater value than the cursor's value, it will get yielded
  # again. Similarly, if the value gets updated to a lesser value than the curor's value, it will get skipped.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#191
  def active_record_on_records(scope, cursor:, **args); end

  # Builds Enumerator object from a given array, using +cursor+ as an offset.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#190
  def array(enumerable, cursor:); end

  # Builds Enumerator from Active Record Relation and enumerates on batches, yielding Active Record Relations.
  # See documentation for #build_active_record_enumerator_on_batches.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#123
  def build_active_record_enumerator_on_batch_relations(scope, cursor:, wrap: T.unsafe(nil), **args); end

  # Builds Enumerator from Active Record Relation and enumerates on batches of records.
  # Each Enumerator tick moves the cursor +batch_size+ rows forward.
  #
  # +batch_size:+ sets how many records will be fetched in one batch. Defaults to 100.
  #
  # For the rest of arguments, see documentation for #build_active_record_enumerator_on_records
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#112
  def build_active_record_enumerator_on_batches(scope, cursor:, **args); end

  # Builds Enumerator from Active Record Relation. Each Enumerator tick moves the cursor one row forward.
  #
  # +columns:+ argument is used to build the actual query for iteration. +columns+: defaults to primary key:
  #
  #   1) SELECT * FROM users ORDER BY id LIMIT 100
  #
  # When iteration is resumed, +cursor:+ and +columns:+ values will be used to continue from the point
  # where iteration stopped:
  #
  #   2) SELECT * FROM users WHERE id > $CURSOR ORDER BY id LIMIT 100
  #
  # +columns:+ can also take more than one column. In that case, +cursor+ will contain serialized values
  # of all columns at the point where iteration stopped.
  #
  # Consider this example with +columns: [:created_at, :id]+. Here's the query will use on the first iteration:
  #
  #   1) SELECT * FROM `products` ORDER BY created_at, id LIMIT 100
  #
  # And the query on the next iteration:
  #
  #   2) SELECT * FROM `products`
  #        WHERE (created_at > '$LAST_CREATED_AT_CURSOR'
  #          OR (created_at = '$LAST_CREATED_AT_CURSOR' AND (id > '$LAST_ID_CURSOR')))
  #        ORDER BY created_at, id LIMIT 100
  #
  # As a result of this query pattern, if the values in these columns change for the records in scope during
  # iteration, they may be skipped or yielded multiple times depending on the nature of the update and the
  # cursor's value. If the value gets updated to a greater value than the cursor's value, it will get yielded
  # again. Similarly, if the value gets updated to a lesser value than the curor's value, it will get skipped.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#97
  def build_active_record_enumerator_on_records(scope, cursor:, **args); end

  # Builds Enumerator object from a given array, using +cursor+ as an offset.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#53
  def build_array_enumerator(enumerable, cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#143
  def build_csv_enumerator(enumerable, cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#148
  def build_csv_enumerator_on_batches(enumerable, cursor:, batch_size: T.unsafe(nil)); end

  # Builds Enumerator for nested iteration.
  #
  # @example
  #   def build_enumerator(cursor:)
  #   enumerator_builder.nested(
  #   [
  #   ->(cursor) {
  #   enumerator_builder.active_record_on_records(Shop.all, cursor: cursor)
  #   },
  #   ->(shop, cursor) {
  #   enumerator_builder.active_record_on_records(shop.products, cursor: cursor)
  #   },
  #   ->(_shop, product, cursor) {
  #   enumerator_builder.active_record_on_batch_relations(product.product_variants, cursor: cursor)
  #   }
  #   ],
  #   cursor: cursor
  #   )
  #   end
  #
  #   def each_iteration(product_variants_relation)
  #   # do something
  #   end
  # @param cursor [Array<Object>] array of offsets for each of the enums to start iteration from
  # @param enums [Array<Proc>] an Array of Procs, each should return an Enumerator.
  #   Each proc from enums should accept the yielded items from the parent enumerators
  #   and the `cursor` as its arguments.
  #   Each proc's `cursor` argument is its part from the `build_enumerator`'s `cursor` array.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#183
  def build_nested_enumerator(enums, cursor:); end

  # Builds Enumerator objects that iterates once.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#41
  def build_once_enumerator(cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#133
  def build_throttle_enumerator(enumerable, throttle_on:, backoff:); end

  # Builds Enumerator objects that iterates N times and yields number starting from zero.
  #
  # @raise [ArgumentError]
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#46
  def build_times_enumerator(number, cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#195
  def csv(enumerable, cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#196
  def csv_on_batches(enumerable, cursor:, batch_size: T.unsafe(nil)); end

  # Builds Enumerator for nested iteration.
  #
  # @example
  #   def build_enumerator(cursor:)
  #   enumerator_builder.nested(
  #   [
  #   ->(cursor) {
  #   enumerator_builder.active_record_on_records(Shop.all, cursor: cursor)
  #   },
  #   ->(shop, cursor) {
  #   enumerator_builder.active_record_on_records(shop.products, cursor: cursor)
  #   },
  #   ->(_shop, product, cursor) {
  #   enumerator_builder.active_record_on_batch_relations(product.product_variants, cursor: cursor)
  #   }
  #   ],
  #   cursor: cursor
  #   )
  #   end
  #
  #   def each_iteration(product_variants_relation)
  #   # do something
  #   end
  # @param cursor [Array<Object>] array of offsets for each of the enums to start iteration from
  # @param enums [Array<Proc>] an Array of Procs, each should return an Enumerator.
  #   Each proc from enums should accept the yielded items from the parent enumerators
  #   and the `cursor` as its arguments.
  #   Each proc's `cursor` argument is its part from the `build_enumerator`'s `cursor` array.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#197
  def nested(enums, cursor:); end

  # Builds Enumerator objects that iterates once.
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#188
  def once(cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#194
  def throttle(enumerable, throttle_on:, backoff:); end

  # Builds Enumerator objects that iterates N times and yields number starting from zero.
  #
  # @raise [ArgumentError]
  #
  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#189
  def times(number, cursor:); end

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#38
  def wrap(*args, **_arg1, &block); end

  private

  # source://job-iteration//lib/job-iteration/enumerator_builder.rb#201
  def build_active_record_enumerator(scope, cursor:, **args); end
end

# These wrappers ensure we have a custom type that we can assert on in
# Iteration. It's useful that the `wrapper` passed to EnumeratorBuilder in
# `enumerator_builder` is _always_ the type that is returned from
# `build_enumerator`. This prevents people from implementing custom
# Enumerators without wrapping them in
# `enumerator_builder.wrap(enumerator_builder, custom_enum)`. Think of these wrappers
# the way you should a middleware.
#
# source://job-iteration//lib/job-iteration/enumerator_builder.rb#21
class JobIteration::EnumeratorBuilder::Wrapper < ::Enumerator
  class << self
    # source://job-iteration//lib/job-iteration/enumerator_builder.rb#23
    def wrap(_builder, enum); end
  end
end

# source://job-iteration//lib/job-iteration/interruption_adapters/null_adapter.rb#5
module JobIteration::InterruptionAdapters
  class << self
    # Returns adapter for specified name.
    #
    #   JobIteration::InterruptionAdapters.lookup(:sidekiq)
    #   # => JobIteration::InterruptionAdapters::SidekiqAdapter
    #
    # source://job-iteration//lib/job-iteration/interruption_adapters.rb#14
    def lookup(name); end

    # Registers adapter for specified name.
    #
    #   JobIteration::InterruptionAdapters.register(:sidekiq, MyCustomSidekiqAdapter)
    #
    # @raise [ArgumentError]
    #
    # source://job-iteration//lib/job-iteration/interruption_adapters.rb#29
    def register(name, adapter); end

    private

    # Returns the value of attribute registry.
    #
    # source://job-iteration//lib/job-iteration/interruption_adapters.rb#37
    def registry; end
  end
end

# @api private
#
# source://job-iteration//lib/job-iteration/interruption_adapters.rb#7
JobIteration::InterruptionAdapters::BUNDLED_ADAPTERS = T.let(T.unsafe(nil), Array)

# source://job-iteration//lib/job-iteration/interruption_adapters/null_adapter.rb#6
module JobIteration::InterruptionAdapters::NullAdapter
  class << self
    # source://job-iteration//lib/job-iteration/interruption_adapters/null_adapter.rb#8
    def call; end
  end
end

# source://job-iteration//lib/job-iteration/interruption_adapters/solid_queue_adapter.rb#20
module JobIteration::InterruptionAdapters::SolidQueueAdapter
  class << self
    # source://job-iteration//lib/job-iteration/interruption_adapters/solid_queue_adapter.rb#24
    def call; end

    # Returns the value of attribute stopping.
    #
    # source://job-iteration//lib/job-iteration/interruption_adapters/solid_queue_adapter.rb#22
    def stopping; end

    # Sets the attribute stopping
    #
    # @param value the value to set the attribute stopping to.
    #
    # source://job-iteration//lib/job-iteration/interruption_adapters/solid_queue_adapter.rb#22
    def stopping=(_arg0); end
  end
end

# source://job-iteration//lib/job-iteration/iteration.rb#6
module JobIteration::Iteration
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::JobIteration::Iteration::ClassMethods

  # source://job-iteration//lib/job-iteration/iteration.rb#85
  def initialize(*arguments, **_arg1); end

  # Returns the value of attribute cursor_position.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#9
  def cursor_position; end

  # Sets the attribute cursor_position
  #
  # @param value the value to set the attribute cursor_position to.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#9
  def cursor_position=(_arg0); end

  # @private
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#103
  def deserialize(job_data); end

  # @private
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#110
  def perform(*params); end

  # source://job-iteration//lib/job-iteration/iteration.rb#116
  def retry_job(*_arg0, **_arg1); end

  # @private
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#95
  def serialize; end

  # The time when the job starts running. If the job is interrupted and runs again, the value is updated.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#15
  def start_time; end

  # The time when the job starts running. If the job is interrupted and runs again, the value is updated.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#15
  def start_time=(_arg0); end

  # source://job-iteration//lib/job-iteration/iteration.rb#9
  def times_interrupted; end

  # source://job-iteration//lib/job-iteration/iteration.rb#9
  def times_interrupted=(_arg0); end

  # The total time (in seconds) the job has been running, including multiple iterations.
  # The time isn't reset if the job is interrupted.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#19
  def total_time; end

  # The total time (in seconds) the job has been running, including multiple iterations.
  # The time isn't reset if the job is interrupted.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#19
  def total_time=(_arg0); end

  private

  # source://job-iteration//lib/job-iteration/iteration.rb#217
  def adjust_total_time; end

  # @raise [ArgumentError]
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#221
  def assert_enumerator!(enum); end

  # source://job-iteration//lib/job-iteration/iteration.rb#255
  def assert_implements_methods!; end

  # The adapter must be able to serialize and deserialize the cursor back into an equivalent object.
  # https://github.com/mperham/sidekiq/wiki/Best-Practices#1-make-your-job-parameters-small-and-simple
  #
  # @raise [CursorError]
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#245
  def assert_valid_cursor!(cursor); end

  # source://job-iteration//lib/job-iteration/iteration.rb#127
  def enumerator_builder; end

  # source://job-iteration//lib/job-iteration/iteration.rb#307
  def handle_completed(completed); end

  # source://job-iteration//lib/job-iteration/iteration.rb#286
  def instrumentation_tags; end

  # source://job-iteration//lib/job-iteration/iteration.rb#131
  def interruptible_perform(*arguments); end

  # @private
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#123
  def interruption_adapter; end

  # source://job-iteration//lib/job-iteration/iteration.rb#173
  def iterate_with_enumerator(enumerator, arguments); end

  # source://job-iteration//lib/job-iteration/iteration.rb#297
  def job_iteration_max_job_runtime; end

  # @return [Boolean]
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#290
  def job_should_exit?; end

  # source://job-iteration//lib/job-iteration/iteration.rb#275
  def method_parameters(method_name); end

  # source://job-iteration//lib/job-iteration/iteration.rb#208
  def reenqueue_iteration_job; end

  # @return [Boolean]
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#340
  def serializable?(object); end

  # @return [Boolean]
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#326
  def valid_cursor_parameter?(parameters); end

  module GeneratedClassMethods
    def job_iteration_max_job_runtime; end
    def job_iteration_max_job_runtime=(value); end
  end

  module GeneratedInstanceMethods; end
end

# source://job-iteration//lib/job-iteration/iteration.rb#56
module JobIteration::Iteration::ClassMethods
  # source://job-iteration//lib/job-iteration/iteration.rb#74
  def around_iterate(&blk); end

  # source://job-iteration//lib/job-iteration/iteration.rb#57
  def method_added(method_name); end

  # source://job-iteration//lib/job-iteration/iteration.rb#70
  def on_complete(*filters, &blk); end

  # source://job-iteration//lib/job-iteration/iteration.rb#66
  def on_shutdown(*filters, &blk); end

  # source://job-iteration//lib/job-iteration/iteration.rb#62
  def on_start(*filters, &blk); end

  private

  # source://job-iteration//lib/job-iteration/iteration.rb#80
  def ban_perform_definition; end
end

# source://job-iteration//lib/job-iteration/iteration.rb#21
class JobIteration::Iteration::CursorError < ::ArgumentError
  # @return [CursorError] a new instance of CursorError
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#24
  def initialize(message, cursor:); end

  # Returns the value of attribute cursor.
  #
  # source://job-iteration//lib/job-iteration/iteration.rb#22
  def cursor; end

  # source://job-iteration//lib/job-iteration/iteration.rb#29
  def message; end

  private

  # source://job-iteration//lib/job-iteration/iteration.rb#35
  def inspected_cursor; end
end

# source://job-iteration//lib/job-iteration/iteration.rb#338
JobIteration::Iteration::SIMPLE_SERIALIZABLE_CLASSES = T.let(T.unsafe(nil), Array)

# source://job-iteration//lib/job-iteration/log_subscriber.rb#4
class JobIteration::LogSubscriber < ::ActiveSupport::LogSubscriber
  # source://job-iteration//lib/job-iteration/log_subscriber.rb#29
  def completed(event); end

  # source://job-iteration//lib/job-iteration/log_subscriber.rb#22
  def interrupted(event); end

  # source://job-iteration//lib/job-iteration/log_subscriber.rb#5
  def logger; end

  # source://job-iteration//lib/job-iteration/log_subscriber.rb#9
  def nil_enumerator(event); end

  # source://job-iteration//lib/job-iteration/log_subscriber.rb#15
  def not_found(event); end
end

# @private
#
# source://job-iteration//lib/job-iteration/nested_enumerator.rb#5
class JobIteration::NestedEnumerator
  # @return [NestedEnumerator] a new instance of NestedEnumerator
  #
  # source://job-iteration//lib/job-iteration/nested_enumerator.rb#6
  def initialize(enums, cursor: T.unsafe(nil)); end

  # source://job-iteration//lib/job-iteration/nested_enumerator.rb#19
  def each(&block); end

  private

  # source://job-iteration//lib/job-iteration/nested_enumerator.rb#27
  def iterate(current_objects, index, &block); end
end

# source://job-iteration//lib/job-iteration/railtie.rb#6
class JobIteration::Railtie < ::Rails::Railtie; end

# ThrottleEnumerator allows you to throttle iterations
# based on external signal (e.g. database health).
# The enumerator from above will mimic +active_record_on_batches+,
# except when +DatabaseStatus.unhealthy?+ starts to return true.
# In that case, it will re-enqueue the job with a specified backoff.
#
# @example
#   def build_enumerator(_params, cursor:)
#   enumerator_builder.build_throttle_enumerator(
#   enumerator_builder.active_record_on_batches(
#   Account.inactive,
#   cursor: cursor
#   ),
#   throttle_on: -> { DatabaseStatus.unhealthy? },
#   backoff: 30.seconds
#   )
#   end
#
# source://job-iteration//lib/job-iteration/throttle_enumerator.rb#21
class JobIteration::ThrottleEnumerator
  # @return [ThrottleEnumerator] a new instance of ThrottleEnumerator
  #
  # source://job-iteration//lib/job-iteration/throttle_enumerator.rb#22
  def initialize(enum, job, throttle_on:, backoff:); end

  # @return [Boolean]
  #
  # source://job-iteration//lib/job-iteration/throttle_enumerator.rb#42
  def should_throttle?; end

  # source://job-iteration//lib/job-iteration/throttle_enumerator.rb#29
  def to_enum; end
end

# source://job-iteration//lib/job-iteration/version.rb#4
JobIteration::VERSION = T.let(T.unsafe(nil), String)
