# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `maintenance_tasks` gem.
# Please instead update this file by running `bin/tapioca gem maintenance_tasks`.


# The engine's namespace module. It provides isolation between the host
# application's code and the engine-specific code. Top-level engine constants
# and variables are defined under this module.
#
# source://maintenance_tasks//lib/maintenance_tasks/engine.rb#5
module MaintenanceTasks
  # source://maintenance_tasks//lib/maintenance_tasks.rb#52
  def active_storage_service; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#52
  def active_storage_service=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#62
  def backtrace_cleaner; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#62
  def backtrace_cleaner=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#30
  def job; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#30
  def job=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#79
  def metadata; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#79
  def metadata=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#72
  def parent_controller; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#72
  def parent_controller=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#110
  def report_errors_as_handled; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#110
  def report_errors_as_handled=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#94
  def status_reload_frequency; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#94
  def status_reload_frequency=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#86
  def stuck_task_duration; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#86
  def stuck_task_duration=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#20
  def tasks_module; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#20
  def tasks_module=(val); end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#43
  def ticker_delay; end

  # source://maintenance_tasks//lib/maintenance_tasks.rb#43
  def ticker_delay=(val); end

  class << self
    # The Active Storage service to use for uploading CSV file blobs.
    #
    # @return [Symbol] the key for the storage service, as specified in the
    #   app's config/storage.yml.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#52
    def active_storage_service; end

    # The Active Storage service to use for uploading CSV file blobs.
    #
    # @return [Symbol] the key for the storage service, as specified in the
    #   app's config/storage.yml.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#52
    def active_storage_service=(val); end

    # The Active Support backtrace cleaner that will be used to clean the
    # backtrace of a Task that errors.
    #
    # @return [ActiveSupport::BacktraceCleaner, nil] the backtrace cleaner to
    #   use when cleaning a Run's backtrace.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#62
    def backtrace_cleaner; end

    # The Active Support backtrace cleaner that will be used to clean the
    # backtrace of a Task that errors.
    #
    # @return [ActiveSupport::BacktraceCleaner, nil] the backtrace cleaner to
    #   use when cleaning a Run's backtrace.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#62
    def backtrace_cleaner=(val); end

    # @api-private
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#133
    def deprecator; end

    # @deprecated
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#119
    def error_handler; end

    # @deprecated
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#126
    def error_handler=(proc); end

    # The name of the job to be used to perform Tasks. Defaults to
    # `"MaintenanceTasks::TaskJob"`. This job must be either a class that
    # inherits from {TaskJob} or a class that includes {TaskJobConcern}.
    #
    # @return [String] the name of the job class.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#30
    def job; end

    # The name of the job to be used to perform Tasks. Defaults to
    # `"MaintenanceTasks::TaskJob"`. This job must be either a class that
    # inherits from {TaskJob} or a class that includes {TaskJobConcern}.
    #
    # @return [String] the name of the job class.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#30
    def job=(val); end

    # source://maintenance_tasks//lib/maintenance_tasks.rb#79
    def metadata; end

    # source://maintenance_tasks//lib/maintenance_tasks.rb#79
    def metadata=(val); end

    # The parent controller all web UI controllers will inherit from.
    # Must be a class that inherits from `ActionController::Base`.
    # Defaults to `"ActionController::Base"`
    #
    # @return [String] the name of the parent controller for web UI.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#72
    def parent_controller; end

    # The parent controller all web UI controllers will inherit from.
    # Must be a class that inherits from `ActionController::Base`.
    # Defaults to `"ActionController::Base"`
    #
    # @return [String] the name of the parent controller for web UI.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#72
    def parent_controller=(val); end

    # source://maintenance_tasks//lib/maintenance_tasks/engine.rb#9
    def railtie_helpers_paths; end

    # source://maintenance_tasks//lib/maintenance_tasks/engine.rb#9
    def railtie_namespace; end

    # source://maintenance_tasks//lib/maintenance_tasks/engine.rb#9
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # How unexpected errors are reported to Rails.error.report.
    #
    # When an error occurs that isn't explicitly handled (e.g., via `report_on`),
    # it gets reported to Rails.error.report. This setting determines whether
    # these errors are marked as "handled" or "unhandled".
    #
    # The current default of `true` is for backwards compatibility, but it prevents
    # error subscribers from distinguishing between expected and unexpected errors.
    # Setting this to `false` provides more accurate error reporting and will become the default in v3.0.
    #
    # @return [Boolean] whether to report unexpected errors as handled (true) or unhandled (false).
    # @see https://api.rubyonrails.org/classes/ActiveSupport/ErrorReporter.html#method-i-report
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#110
    def report_errors_as_handled; end

    # How unexpected errors are reported to Rails.error.report.
    #
    # When an error occurs that isn't explicitly handled (e.g., via `report_on`),
    # it gets reported to Rails.error.report. This setting determines whether
    # these errors are marked as "handled" or "unhandled".
    #
    # The current default of `true` is for backwards compatibility, but it prevents
    # error subscribers from distinguishing between expected and unexpected errors.
    # Setting this to `false` provides more accurate error reporting and will become the default in v3.0.
    #
    # @return [Boolean] whether to report unexpected errors as handled (true) or unhandled (false).
    # @see https://api.rubyonrails.org/classes/ActiveSupport/ErrorReporter.html#method-i-report
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#110
    def report_errors_as_handled=(val); end

    # The frequency at which to reload the run status during iteration.
    # Defaults to 1 second, meaning reload status every second.
    #
    # @return [ActiveSupport::Duration, Numeric] the time interval between status reloads.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#94
    def status_reload_frequency; end

    # The frequency at which to reload the run status during iteration.
    # Defaults to 1 second, meaning reload status every second.
    #
    # @return [ActiveSupport::Duration, Numeric] the time interval between status reloads.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#94
    def status_reload_frequency=(val); end

    # The duration after which a task is considered stuck and can be force cancelled.
    #
    # @return [ActiveSupport::Duration] the threshold in seconds after which a task is considered stuck.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#86
    def stuck_task_duration; end

    # The duration after which a task is considered stuck and can be force cancelled.
    #
    # @return [ActiveSupport::Duration] the threshold in seconds after which a task is considered stuck.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#86
    def stuck_task_duration=(val); end

    # source://maintenance_tasks//lib/maintenance_tasks/engine.rb#9
    def table_name_prefix; end

    # The module to namespace Tasks in, as a String. Defaults to 'Maintenance'.
    #
    # @return [String] the name of the module.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#20
    def tasks_module; end

    # The module to namespace Tasks in, as a String. Defaults to 'Maintenance'.
    #
    # @return [String] the name of the module.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#20
    def tasks_module=(val); end

    # The delay between updates to the tick count. After each iteration, the
    # progress of the Task may be updated. This duration in seconds limits
    # these updates, skipping if the duration since the last update is lower
    # than this value, except if the job is interrupted, in which case the
    # progress will always be recorded.
    #
    # @return [ActiveSupport::Duration, Numeric] duration of the delay between
    #   updates to the tick count during Task iterations.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#43
    def ticker_delay; end

    # The delay between updates to the tick count. After each iteration, the
    # progress of the Task may be updated. This duration in seconds limits
    # these updates, skipping if the duration since the last update is lower
    # than this value, except if the job is interrupted, in which case the
    # progress will always be recorded.
    #
    # @return [ActiveSupport::Duration, Numeric] duration of the delay between
    #   updates to the tick count during Task iterations.
    #
    # source://maintenance_tasks//lib/maintenance_tasks.rb#43
    def ticker_delay=(val); end

    # source://maintenance_tasks//lib/maintenance_tasks/engine.rb#9
    def use_relative_model_naming?; end
  end
end

class MaintenanceTasks::ApplicationController < ::ActionController::Base
  private

  def _layout(lookup_context, formats, keys); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

MaintenanceTasks::ApplicationController::BULMA_CDN = T.let(T.unsafe(nil), String)

module MaintenanceTasks::ApplicationController::HelperMethods
  include ::InertiaRails::Helper
  include ::ViteRails::TagHelpers
  include ::ActionController::Base::HelperMethods
  include ::MaintenanceTasks::ApplicationHelper
end

module MaintenanceTasks::ApplicationHelper
  def time_ago(datetime); end
end

class MaintenanceTasks::ApplicationRecord < ::ActiveRecord::Base
  include ::MaintenanceTasks::ApplicationRecord::GeneratedAttributeMethods
  include ::MaintenanceTasks::ApplicationRecord::GeneratedAssociationMethods

  class << self
    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module MaintenanceTasks::ApplicationRecord::GeneratedAssociationMethods; end
module MaintenanceTasks::ApplicationRecord::GeneratedAttributeMethods; end

class MaintenanceTasks::BatchCsvCollectionBuilder < ::MaintenanceTasks::CsvCollectionBuilder
  def initialize(batch_size, **csv_options); end

  def collection(task); end
  def count(task); end
end

class MaintenanceTasks::BatchCsvCollectionBuilder::BatchCsv < ::Struct
  def batch_size; end
  def batch_size=(_); end
  def csv; end
  def csv=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class MaintenanceTasks::CsvCollectionBuilder
  def initialize(**csv_options); end

  def collection(task); end
  def count(task); end
  def has_csv_content?; end
  def no_collection?; end
end

# The engine's main class, which defines its namespace. The engine is mounted
# by the host application.
#
# source://maintenance_tasks//lib/maintenance_tasks/engine.rb#8
class MaintenanceTasks::Engine < ::Rails::Engine; end

class MaintenanceTasks::NoCollectionBuilder
  def collection(_task); end
  def count(_task); end
  def has_csv_content?; end
  def no_collection?; end
end

class MaintenanceTasks::NullCollectionBuilder
  def collection(task); end
  def count(task); end
  def has_csv_content?; end
  def no_collection?; end
end

class MaintenanceTasks::Progress
  include ::ActiveSupport::NumberHelper
  include ::ActionView::Helpers::SanitizeHelper
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper
  include ::ActionView::Helpers::TextHelper
  extend ::ActionView::Helpers::SanitizeHelper::ClassMethods

  def initialize(run); end

  def max; end
  def text; end
  def value; end

  private

  def estimatable?; end
  def over_total?; end
  def total?; end
end

class MaintenanceTasks::Run < ::MaintenanceTasks::ApplicationRecord
  include ::MaintenanceTasks::Run::GeneratedAttributeMethods
  include ::MaintenanceTasks::Run::GeneratedAssociationMethods
  include ::MaintenanceTasks::RunConcern

  def _run_commit_callbacks(&block); end
  def _run_create_callbacks(&block); end
  def _run_destroy_callbacks(&block); end
  def _run_save_callbacks(&block); end
  def _run_update_callbacks(&block); end
  def autosave_associated_records_for_csv_file_attachment(*args); end
  def autosave_associated_records_for_csv_file_blob(*args); end
  def enqueued!; end

  class << self
    def active(*args, **_arg1); end
    def cancelled(*args, **_arg1); end
    def cancelling(*args, **_arg1); end
    def completed(*args, **_arg1); end
    def enqueued(*args, **_arg1); end
    def errored(*args, **_arg1); end
    def interrupted(*args, **_arg1); end
    def not_cancelled(*args, **_arg1); end
    def not_cancelling(*args, **_arg1); end
    def not_enqueued(*args, **_arg1); end
    def not_errored(*args, **_arg1); end
    def not_interrupted(*args, **_arg1); end
    def not_paused(*args, **_arg1); end
    def not_pausing(*args, **_arg1); end
    def not_running(*args, **_arg1); end
    def not_succeeded(*args, **_arg1); end
    def paused(*args, **_arg1); end
    def pausing(*args, **_arg1); end
    def running(*args, **_arg1); end
    def statuses; end
    def succeeded(*args, **_arg1); end
    def with_attached_csv(*args, **_arg1); end
    def with_attached_csv_file(*args, **_arg1); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__attr_readonly; end
    def __class_attr__attr_readonly=(new_value); end
    def __class_attr__reflections; end
    def __class_attr__reflections=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_attachment_reflections; end
    def __class_attr_attachment_reflections=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module MaintenanceTasks::Run::GeneratedAssociationMethods
  def build_csv_file_attachment(*args, &block); end
  def build_csv_file_blob(*args, &block); end
  def create_csv_file_attachment(*args, &block); end
  def create_csv_file_attachment!(*args, &block); end
  def create_csv_file_blob(*args, &block); end
  def create_csv_file_blob!(*args, &block); end
  def csv_file; end
  def csv_file=(attachable); end
  def csv_file_attachment; end
  def csv_file_attachment=(value); end
  def csv_file_blob; end
  def csv_file_blob=(value); end
  def reload_csv_file_attachment; end
  def reload_csv_file_blob; end
  def reset_csv_file_attachment; end
  def reset_csv_file_blob; end
end

module MaintenanceTasks::Run::GeneratedAttributeMethods; end

module MaintenanceTasks::RunConcern
  extend ::ActiveSupport::Concern

  def active?; end
  def cancel; end
  def complete; end
  def completed?; end
  def csv_attachment_presence; end
  def csv_content_type; end
  def csv_file; end
  def job_shutdown; end
  def masked_arguments; end
  def pause; end
  def persist_error(error); end
  def persist_progress(number_of_ticks, duration); end
  def persist_transition; end
  def reload_status; end
  def running; end
  def start(count); end
  def started?; end
  def stopped?; end
  def stopping?; end
  def stuck?; end
  def task; end
  def task_name_belongs_to_a_valid_task; end
  def time_to_completion; end
  def validate_task_arguments; end

  private

  def argument_filter; end
  def arguments_match_task_attributes; end
  def instrument_status_change; end
  def run_error_callback; end
  def run_task_callbacks(callback); end
  def stale_object_retry_delay(retry_count); end
  def truncate(attribute_name, value); end
  def with_stale_object_retry(retry_count = T.unsafe(nil)); end
end

MaintenanceTasks::RunConcern::ACTIVE_STATUSES = T.let(T.unsafe(nil), Array)
MaintenanceTasks::RunConcern::CALLBACKS_TRANSITION = T.let(T.unsafe(nil), Hash)
MaintenanceTasks::RunConcern::COMPLETED_STATUSES = T.let(T.unsafe(nil), Array)
MaintenanceTasks::RunConcern::DELAYS_PER_ATTEMPT = T.let(T.unsafe(nil), Array)
MaintenanceTasks::RunConcern::MAX_RETRIES = T.let(T.unsafe(nil), Integer)
MaintenanceTasks::RunConcern::STATUSES = T.let(T.unsafe(nil), Array)
MaintenanceTasks::RunConcern::STOPPING_STATUSES = T.let(T.unsafe(nil), Array)

class MaintenanceTasks::RunStatusValidator < ::ActiveModel::Validator
  def validate(record); end

  private

  def add_invalid_status_error(record, previous_status, new_status); end
end

MaintenanceTasks::RunStatusValidator::VALID_STATUS_TRANSITIONS = T.let(T.unsafe(nil), Hash)

module MaintenanceTasks::Runner
  extend ::MaintenanceTasks::Runner

  def resume(run); end
  def run(name:, csv_file: T.unsafe(nil), arguments: T.unsafe(nil), run_model: T.unsafe(nil), metadata: T.unsafe(nil)); end

  private

  def enqueue(run, job); end
  def filename(task_name); end
  def instantiate_job(run); end
end

class MaintenanceTasks::Runner::EnqueuingError < ::StandardError
  def initialize(run); end

  def run; end
end

class MaintenanceTasks::RunsController < ::MaintenanceTasks::ApplicationController
  def cancel; end
  def create(&block); end
  def pause; end
  def resume; end

  private

  def _layout(lookup_context, formats, keys); end
  def set_run; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module MaintenanceTasks::RunsController::HelperMethods
  include ::InertiaRails::Helper
  include ::ViteRails::TagHelpers
  include ::ActionController::Base::HelperMethods
  include ::MaintenanceTasks::ApplicationHelper
  include ::MaintenanceTasks::ApplicationController::HelperMethods
  include ::MaintenanceTasks::TasksHelper
end

class MaintenanceTasks::RunsPage
  def initialize(runs, cursor); end

  def cursor; end
  def last?; end
  def next_cursor; end
  def records; end
end

MaintenanceTasks::RunsPage::RUNS_PER_PAGE = T.let(T.unsafe(nil), Integer)

class MaintenanceTasks::Task
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::AttributeRegistration
  include ::ActiveModel::AttributeMethods
  include ::ActiveModel::Attributes
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::Validations
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveSupport::Rescuable
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveModel::AttributeRegistration::ClassMethods
  extend ::ActiveModel::AttributeMethods::ClassMethods
  extend ::ActiveModel::Attributes::ClassMethods
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveSupport::Rescuable::ClassMethods

  def __callbacks; end
  def _cancel_callbacks; end
  def _complete_callbacks; end
  def _error_callbacks; end
  def _interrupt_callbacks; end
  def _pause_callbacks; end
  def _run_cancel_callbacks; end
  def _run_cancel_callbacks!(&block); end
  def _run_complete_callbacks; end
  def _run_complete_callbacks!(&block); end
  def _run_error_callbacks; end
  def _run_error_callbacks!(&block); end
  def _run_interrupt_callbacks; end
  def _run_interrupt_callbacks!(&block); end
  def _run_pause_callbacks; end
  def _run_pause_callbacks!(&block); end
  def _run_start_callbacks; end
  def _run_start_callbacks!(&block); end
  def _run_validate_callbacks; end
  def _run_validate_callbacks!(&block); end
  def _start_callbacks; end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def active_record_enumerator_batch_size; end
  def active_record_enumerator_batch_size=(_arg0); end
  def active_record_enumerator_batch_size?; end
  def attribute_aliases; end
  def attribute_aliases?; end
  def attribute_method_patterns; end
  def attribute_method_patterns?; end
  def collection; end
  def collection_builder_strategy; end
  def collection_builder_strategy=(_arg0); end
  def collection_builder_strategy?; end
  def count; end
  def csv_content; end
  def csv_content=(csv_content); end
  def cursor_columns; end
  def enumerator_builder(cursor:); end
  def has_csv_content?; end
  def masked_arguments; end
  def masked_arguments=(_arg0); end
  def masked_arguments?; end
  def metadata; end
  def metadata=(_arg0); end
  def model_name(&_arg0); end
  def no_collection?; end
  def process(_item); end
  def rescue_handlers; end
  def rescue_handlers=(_arg0); end
  def rescue_handlers?; end
  def status_reload_frequency; end
  def status_reload_frequency=(_arg0); end
  def status_reload_frequency?; end
  def throttle_conditions; end
  def throttle_conditions=(_arg0); end
  def throttle_conditions?; end

  class << self
    def __callbacks; end
    def __callbacks=(value); end
    def _cancel_callbacks; end
    def _cancel_callbacks=(value); end
    def _complete_callbacks; end
    def _complete_callbacks=(value); end
    def _error_callbacks; end
    def _error_callbacks=(value); end
    def _interrupt_callbacks; end
    def _interrupt_callbacks=(value); end
    def _pause_callbacks; end
    def _pause_callbacks=(value); end
    def _start_callbacks; end
    def _start_callbacks=(value); end
    def _validate_callbacks; end
    def _validate_callbacks=(value); end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
    def active_record_enumerator_batch_size; end
    def active_record_enumerator_batch_size=(value); end
    def active_record_enumerator_batch_size?; end
    def after_cancel(*filter_list, &block); end
    def after_complete(*filter_list, &block); end
    def after_error(*filter_list, &block); end
    def after_interrupt(*filter_list, &block); end
    def after_pause(*filter_list, &block); end
    def after_start(*filter_list, &block); end
    def attribute_aliases; end
    def attribute_aliases=(value); end
    def attribute_aliases?; end
    def attribute_method_patterns; end
    def attribute_method_patterns=(value); end
    def attribute_method_patterns?; end
    def available_tasks; end
    def collection; end
    def collection_batch_size(size); end
    def collection_builder_strategy; end
    def collection_builder_strategy=(value); end
    def collection_builder_strategy?; end
    def count; end
    def csv_collection(in_batches: T.unsafe(nil), **csv_options); end
    def has_csv_content?(*_arg0, **_arg1, &_arg2); end
    def load_all; end
    def mask_attribute(*attributes); end
    def masked_arguments; end
    def masked_arguments=(value); end
    def masked_arguments?; end
    def named(name); end
    def no_collection; end
    def no_collection?(*_arg0, **_arg1, &_arg2); end
    def process(*args); end
    def reload_status_every(frequency); end
    def report_on(*exceptions, **report_options); end
    def rescue_handlers; end
    def rescue_handlers=(value); end
    def rescue_handlers?; end
    def status_reload_frequency; end
    def status_reload_frequency=(value); end
    def status_reload_frequency?; end
    def throttle_conditions; end
    def throttle_conditions=(value); end
    def throttle_conditions?; end
    def throttle_on(backoff: T.unsafe(nil), &condition); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_active_record_enumerator_batch_size; end
    def __class_attr_active_record_enumerator_batch_size=(new_value); end
    def __class_attr_attribute_aliases; end
    def __class_attr_attribute_aliases=(new_value); end
    def __class_attr_attribute_method_patterns; end
    def __class_attr_attribute_method_patterns=(new_value); end
    def __class_attr_collection_builder_strategy; end
    def __class_attr_collection_builder_strategy=(new_value); end
    def __class_attr_masked_arguments; end
    def __class_attr_masked_arguments=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
    def __class_attr_status_reload_frequency; end
    def __class_attr_status_reload_frequency=(new_value); end
    def __class_attr_throttle_conditions; end
    def __class_attr_throttle_conditions=(new_value); end
    def load_constants; end
  end
end

class MaintenanceTasks::Task::NotFoundError < ::NameError; end

class MaintenanceTasks::TaskDataIndex
  def initialize(name, related_run = T.unsafe(nil)); end

  def category; end
  def name; end
  def related_run; end
  def status; end
  def to_s; end

  class << self
    def available_tasks; end
  end
end

class MaintenanceTasks::TaskDataShow
  def initialize(name, runs_cursor: T.unsafe(nil), arguments: T.unsafe(nil)); end

  def active_runs; end
  def code; end
  def completed_runs; end
  def csv_task?; end
  def deleted?; end
  def ensure_task_exists; end
  def load_active_runs; end
  def name; end
  def new; end
  def parameter_names; end
  def refresh?; end
  def runs_page; end
  def to_s; end

  private

  def runs; end

  class << self
    def prepare(name, runs_cursor: T.unsafe(nil), arguments: T.unsafe(nil)); end
  end
end

class MaintenanceTasks::TaskJob < ::ActiveJob::Base
  include ::JobIteration::Iteration
  include ::MaintenanceTasks::TaskJobConcern
  extend ::JobIteration::Iteration::ClassMethods
  extend ::MaintenanceTasks::TaskJobConcern::ClassMethods

  def _complete_callbacks; end
  def _iterate_callbacks; end
  def _run_complete_callbacks(&block); end
  def _run_complete_callbacks!(&block); end
  def _run_iterate_callbacks; end
  def _run_iterate_callbacks!(&block); end
  def _run_perform_callbacks(&block); end
  def _run_shutdown_callbacks(&block); end
  def _run_shutdown_callbacks!(&block); end
  def _run_start_callbacks(&block); end
  def _run_start_callbacks!(&block); end
  def _shutdown_callbacks; end
  def _start_callbacks; end

  class << self
    def _complete_callbacks; end
    def _complete_callbacks=(value); end
    def _iterate_callbacks; end
    def _iterate_callbacks=(value); end
    def _shutdown_callbacks; end
    def _shutdown_callbacks=(value); end
    def _start_callbacks; end
    def _start_callbacks=(value); end
    def job_iteration_max_job_runtime; end
    def job_iteration_max_job_runtime=(value); end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr_job_iteration_max_job_runtime; end
    def __class_attr_job_iteration_max_job_runtime=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

module MaintenanceTasks::TaskJobConcern
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods
  include ::JobIteration::Iteration

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::JobIteration::Iteration::ClassMethods
  mixes_in_class_methods ::MaintenanceTasks::TaskJobConcern::ClassMethods

  private

  def after_perform; end
  def before_perform; end
  def build_enumerator(_run, cursor:); end
  def each_iteration(input, _run); end
  def on_complete; end
  def on_error(error); end
  def on_shutdown; end
  def on_start; end
  def reenqueue_iteration_job(should_ignore: T.unsafe(nil)); end
  def reload_run_status; end
  def should_reload_status?; end
  def task_iteration(input); end
  def throttle_enumerator(collection_enum); end

  module GeneratedClassMethods
    def job_iteration_max_job_runtime; end
    def job_iteration_max_job_runtime=(value); end
  end

  module GeneratedInstanceMethods; end
end

module MaintenanceTasks::TaskJobConcern::ClassMethods
  def retry_on(*_arg0, **_arg1); end
end

class MaintenanceTasks::TasksController < ::MaintenanceTasks::ApplicationController
  def index; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def set_refresh; end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
  end
end

module MaintenanceTasks::TasksController::HelperMethods
  include ::InertiaRails::Helper
  include ::ViteRails::TagHelpers
  include ::ActionController::Base::HelperMethods
  include ::MaintenanceTasks::ApplicationHelper
  include ::MaintenanceTasks::ApplicationController::HelperMethods
  include ::MaintenanceTasks::TasksHelper
end

module MaintenanceTasks::TasksHelper
  def attribute_required?(task, parameter_name); end
  def csv_file_download_path(run); end
  def datetime_field_help_text; end
  def format_backtrace(backtrace); end
  def highlight_code(code); end
  def parameter_field(form_builder, parameter_name); end
  def progress(run); end
  def resolve_inclusion_value(task, parameter_name); end
  def status_tag(status); end
  def time_running_in_words(run); end
end

MaintenanceTasks::TasksHelper::STATUS_COLOURS = T.let(T.unsafe(nil), Hash)

class MaintenanceTasks::Ticker
  def initialize(throttle_duration, &persist); end

  def persist; end
  def tick; end

  private

  def persist?; end
end
