# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `standard-rspec` gem.
# Please instead update this file by running `bin/tapioca gem standard-rspec`.


# source://standard-rspec//lib/standard/rspec/version.rb#3
module Standard; end

# source://standard-rspec//lib/standard/rspec/version.rb#4
module Standard::Rspec; end

# source://standard-rspec//lib/standard/rspec/plugin.rb#9
class Standard::Rspec::Plugin < ::LintRoller::Plugin
  # source://standard-rspec//lib/standard/rspec/plugin.rb#10
  def about; end

  # source://standard-rspec//lib/standard/rspec/plugin.rb#23
  def rules(context); end

  # @return [Boolean]
  #
  # source://standard-rspec//lib/standard/rspec/plugin.rb#19
  def supported?(context); end
end

# source://standard-rspec//lib/standard/rspec/version.rb#5
Standard::Rspec::VERSION = T.let(T.unsafe(nil), String)
